### ISSUE TITLE
Multiple forms in single page

### ISSUE THREAD

**Issue by geogeorgejoseph** [getgrav/grav-plugin-form#181]
In my home page i am added two forms, one is simple search form and other one is contact form.I am added recaptcha in contact form.but after submitting the search form getting some alert showing "Error validating the Captcha".Can you suggest solution for this issue

**Comment by rhukster** [comment]
I think this should resolve it: https://github.com/getgrav/grav-plugin-form/issues/182

**Comment by hexplor** [comment]
Hey @rhukster ,
This fix will not work on multiple forms in **modular** pages. You will get:

"Uncaught Error: reCAPTCHA has already been rendered in this element"

Only solution is to provide unique callback names and field id names. Here's very dirty fix for captcha.html.twig :)

```
{% extends "forms/field.html.twig" %}

{% block input %}
    <script>
        var captchaOnloadCallback{{ field.name }} = function captchaOnloadCallback{{ field.name }}() {
            grecaptcha.render('{{ field.name }}', {
                'sitekey': "{{field.recaptcha_site_key ?: field.recaptcha_site_key ?: config.plugins.form.recaptcha.site_key }}",
                'callback': captchaValidatedCallback,
                'expired-callback': captchaExpiredCallback
            });
        };

        var captchaValidatedCallback = function captchaValidatedCallback() {

        };

        var captchaExpiredCallback = function captchaExpiredCallback() {
            grecaptcha.reset();
        };

        $('form').submit(function(event) {
            if ($(this).has("#{{ field.name }}-response").length && $("#{{ field.name }}-response").val() === '') {
                event.preventDefault();
                alert("{{grav.language.translate('PLUGIN_FORM.ERROR_VALIDATING_CAPTCHA')}}");
            }
        });
    </script>
    <script src="https://www.google.com/recaptcha/api.js?onload=captchaOnloadCallback{{ field.name }}&render=explicit&hl={{ grav.language.language }}"
        async defer>
    </script>
    <div class="{{ field.name }}" id="{{ field.name }}" data-theme="{{ page.header.captcha }}"></div>
{% endblock %}

```

**Comment by mahagr** [comment]
@w00fz I believe you have already fixed this?

**Comment by w00fz** [comment]
Yeah I remember adding the missing support for multiple reCaptcha on multiple forms on the same page for both v2 and v3.
We have tests in demo samples as well and should be in the changelog too.

Feel free to reopen if this issue persists!

**Comment by marknokes** [comment]
This is still an issue for me in conjunction with the [Comments Plugin](https://github.com/getgrav/grav-plugin-comments). I would open the issue there, but it doesn't look like that plugin is still being developed.

 I have recaptcha v3 enabled for the comments form, and placed a form created with this plugin in my sidebar, also with recaptcha v3. The sidebar form always seems to validate properly, but the comments form (when submitted) will display the "Invalid Captcha" message, but not actually prevent the comment from submitting or email from going through.

Any ideas?

**Comment by mahagr** [comment]
It might be a better idea to open a new issue instead of commenting on a closed one. Maybe to the comments plugin?

**Comment by marknokes** [comment]
I decided to abandon the comments plugin all together. It was causing too much headache. Thanks.
