### ISSUE TITLE
Form 7.3.0 Cloudflare Turnstile Captcha Help Text

### ISSUE THREAD

**Issue by PalmTreeVI** [getgrav/grav-plugin-form#594]
Small nit. Form 7.3.0 Cloudflare Turnstile Captcha settings help text for "Site Key" and "Secret Key" have Google help text.
![Screenshot_2024-02-14_07-58-58](https://github.com/getgrav/grav-plugin-form/assets/64500998/a60eb61d-0a63-4740-a3d2-a1d15045ca79)

**Comment by sridharkalaibala** [comment]
This appears addressed in current develop (`324a42b`, blueprint version 9.1.24). I parsed the actual blueprint and English translations: `turnstile.site_key` uses `PLUGIN_FORM.TURNSTILE_SITE_KEY_HELP`, and `turnstile.secret_key` uses `PLUGIN_FORM.TURNSTILE_SECRET_KEY_HELP`; both resolve to `https://developers.cloudflare.com/turnstile/`, with no Google reference.

Sources: [Turnstile field definitions](https://github.com/getgrav/grav-plugin-form/blob/324a42b5e6fd5c226c8b8c3c361a7519496e6945/blueprints.yaml#L238-L246) and [English help text](https://github.com/getgrav/grav-plugin-form/blob/324a42b5e6fd5c226c8b8c3c361a7519496e6945/languages.yaml#L93-L95).

This verifies the current source bindings, not an Admin browser session on the originally reported 7.3.0 installation. If it still occurs on a newer installation, the installed version and any language overrides would help narrow it down.

**Comment by rhukster** [comment]
This one's already resolved — the Turnstile site key and secret key help text now points at Cloudflare's documentation rather than Google's reCAPTCHA docs, shipped in 9.1.24.

The field labels were still showing reCAPTCHA wording, which [#590](https://github.com/getgrav/grav-plugin-form/issues/590) picked up and is fixed for 9.1.25.

Thanks for the report.
